### ISSUE TITLE
file name of tikz file ignored

### ISSUE THREAD

**Issue by Druidefix** [Fiech/surf3tikz#1]
The specified file name is not used in the source code of the tikz file.

line 375
`[~, export_fname, ~] = fileparts('../../LaTeX/wuff');`
should be removed and line 410 should be changed to
`fprintf(tfile_h, '\t \t }]{%s.png};\n', export_name);`

**Comment by Fiech** [comment]
l. 375 is as of now fixed but l.410 is correct, because in the tikz file the path to the png file has to be relative to the tikz file. If you would execute the function with a relative path, the path in the tikz file itself would be relative therefore leadiing to the build process failing.
