### ISSUE TITLE
imagesc plot conversion: colorbar scale ignored

### ISSUE THREAD

**Issue by Druidefix** [Fiech/surf3tikz#4]
Consider the following example

```
cfg.s3t.use_imagesc = true;
surf(randn(10), 'EdgeColor','None')
colorbar
caxis([-10 0])
view(0,90)
surf3tikz(gcf, 'schlendi', cfg.s3t)
```

where the colorbar is changed. The resulting png image is though created with the original colorbar scaling.

**Comment by Fiech** [comment]
New version now respects climits, even when no colorbar is set in the figure
