### ISSUE TITLE
surf3tikz does ignore "reverse" direction for axis when using imagesc option

### ISSUE THREAD

**Issue by Druidefix** [Fiech/surf3tikz#6]
The current version of `surf3tikz` ignores a reversed axis.

Consider the following minimal not working example:

    foo = zeros(10,10);
    foo(2,2) = 1;
    
    figure(1)
    clf
    surf(1:10, [-5:4], foo)
    view(-90,90)
    set(gca,'YDir','reverse')
    
    cfg.s3t.use_imagesc = true;
    
    surf3tikz(gcf, 'foo', cfg.s3t)

The output is the same as if the option `set(gca,'YDir','reverse')` is not set. In this case in the `tikz` file the line `x dir = reverse,` can be commented and the `png` can be flipped with `mogrify -flop foo.png` to get the desired output.

**Comment by Fiech** [comment]
Ok, so the problem was, that I never considered the direction option in the first place, which leads to wrong axis in the 2D Plot and additionally a wrong png file for the imagesc option. I now take the axis direction into account....
